// PressurePlateModel.cs (auto‑generated by Normcore’s codegen)
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PressurePlateModel
{
    [RealtimeProperty(1, true, true)]
    private bool _pressed;
}